### ISSUE TITLE
Notes hardware

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/electric-kart#2]
# Notes Board V2.1

## issues / next version
- temperaturesensor for 
   - igbt
   - motor
- simply route some reserve gpio pins to screw terminals
- potentiometer for voltage threshold:  its hard to precicely set volte -> more resolution in actually relevant range (add fixed resistor for offset)
- pullup resistor for UART RX pin: prevent unnecessary interrupts since nothing is connected most of the time
- ~~Mosfet output does not switch off / on completely - mosfet was bad initially~~

## Tasks
- [x] reduce gate resistor after driver <10 ohm for less switching losses - reduced to 2x15ohm (7.5)
- [x] 18V 1.5A supply powerfull enough? - ok 0.5V ripple at 14kHz pwm with 10ohm R
- [x] replace mosfet / change resistors
  - [ ] update schematic with other mosfet type
